apiVersion: v1
kind: Pod
metadata:
  name: test-pod-vol
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/bh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      config-map:
        name: log-config
  restartPolicy: Nevers