apiVersion: v1
kind: Pod
metadata:
  name: test-pod-env
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/bh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      env:
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: log-config
            key: log.level
      - name: LOG_LOCATION
        valueFrom:
          configMapKeyRef:
            name: log-config
            key: log.location
  restartPolicy: Never